import java.util.*;
import java.lang.*;
import java.io.*;

class Employee
{
//attributes of Employee class
private String firstName;
private String lastName;
private int employeeID;
private double salary;
public Employee()                          //default constructor
{
  firstName=null;
  lastName=null;
  employeeID=0;
  salary=0.0;
  
}
public void setFirstName(String fname)       //set and get methods for all attributes
{
  firstName = fname;
}
public String getFirstname()
{
  return firstName;
}
public void setLastName(String lname)
{
  lastName = lname;
}
public String getLastName()
{
  return lastName;
}
public void setEmployeeID(int empId)
{
  employeeID = empId;
  
}
public double getEmployeeID()
{
  return employeeID;
}
public void setSalary(double s)
{
  salary=s;
}
public double getSalary()
{
  return salary;
}
public void EmployeeSummary()       //display all attributes of Employee class
{
  System.out.println("Employee Name: "+ fname +" " +lname+" Employee Id : "+empID + " salary: "+salary);
}
}
class Manager extends Employee          
{
private String department;
public Manager()                       //default constructor
{
  super();                           //calling superor base class default constructor
  department = null;
}
public void setDepartment(String dept)        //set and get methods for department
{
  department=dept;
}
public String getDepartment()
{
  return department;
}
public void EmployeeSummary()
{
  super.EmployeeSummary();     //calling super class method with same name
  System.out.println("Department : "+department);
}
}

class TestEmployee
{
public static void main (String[] args)
{
  Manager mgr=new Manager();
  mgr.setFirstName("Charles");        //all set methods of super class are available to derived class
  mgr.setLastName("Dickens");
  mgr.setEmployeeID(34599);
  mgr.setSalary(6500);
  mgr.setDepartment("Accounts");
  mgr.EmployeeSummary();
}
}
